spring:
  application:
    name: Bookository - учебный проект. Сайт электронной библиотеки
  datasource:
    url: ${DB_JDBC_URL:jdbc:postgresql://localhost:5432/bookository}?currentSchema=bookository
    hikari:
      driver-class-name: org.postgresql.Driver
      pool-name: HikariCpPoolName
      username: ${DB_USER:postgres}
      password: ${DB_PWD:postgres}
      connectionTimeout: ${DB_TIMEOUT:30000}
      maximum-pool-size: ${DB_POOL_SIZE:10}
      schema: bookository
      connection-init-sql: "SELECT 1"
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 50MB
      location:
  jpa:
    hibernate:
      show-sql: true
      format_sql: true
      use_sql_comments: true
      #ddl-auto: validate
# Добавить метку о способе сортировки nullable значений. См книгу jpa & hibernate!!

server:
  port: 8020

app:
  system-offset-id: ${SYSTEM-OFFSET-ID:+03}

springdoc:
  swagger-ui:
    path: "/bookository-swagger"
  api-docs:
    path: "/v1/bookository-api-docs"
    enabled: true