server:
  port: ${MIGRATION_SERVER_PORT:8030}

spring:
  application:
    name: ^project.name^

liquibase:
  change-log-path: ${MIGRATION_CHANGE_LOG_PATH:classpath:db/changelog}
  default-schema: ${MIGRATION_DEFAULT_SCHEMA:public}

springdoc:
  api-docs:
    path: "/api-docs"
    enabled: true
  swagger-ui:
    path: "/bookository-migration-swagger"