version: "3"
services:
  adminer:
    image: adminer:4.8.1
    restart: on-failure
    ports:
      - "8010:8080"

  postgres:
    image: bookository/postgres:br_it
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookository

  bookository-server:
    image: bookository/bookository-server:br_it
    restart: on-failure
    ports:
      - "8020:8020"
      - "38005:38005"
    environment:
      DB_JDBC_URL: jdbc:postgresql://postgres:5432/bookository?currentSchema=bookository
      DB_USER: "postgres"
      DB_PWD: "postgres"
    depends_on:
      - postgres