services:
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8010:8080"
    networks:
      bookository-default-network:
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    networks:
      bookository-default-network:
    volumes:
      - bookository-db-volume:/var/lib/postgresql/data
      - "./resources/covers/:/opt/covers:ro"
      - "./resources/books/:/opt/books:ro"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookository

  bookository-server:
    image: "bookository/bookository-server:${IMAGE_VERSION}"
    restart: on-failure
    ports:
      - "8020:8020"
      - "38005:38005"
    networks:
      bookository-default-network:
    environment:
      DB_JDBC_URL: jdbc:postgresql://postgres:5432/bookository?currentSchema=bookository
      DB_USER: "postgres"
      DB_PWD: "postgres"
    depends_on:
      - postgres

  bookository-migration:
    image: "bookository/bookository-migration:${IMAGE_VERSION}"
    restart: on-failure
    ports:
      - "8030:8030"
      - "38006:38006"
    networks:
      bookository-default-network:
    environment:
      MIGRATION_SERVER_PORT: 8030
      MIGRATION_CHANGE_LOG_PATH: "classpath:db/changelog"
      MIGRATION_DEFAULT_SCHEMA: "public"
    depends_on:
      - postgres

#  bookository-web:
#    image: bookository/bookository-web:br_it
#    restart: on-failure
#    network_mode: bridge
#    ports:
#      - "81:3000"
#    networks:
#      bookository-default-network:
#
#    environment:
#      API_HOST: "http://localhost:8020/api"

networks:
  bookository-default-network:
    driver: bridge

volumes:
  bookository-db-volume:
