FROM postgres:15.3
WORKDIR /opt
RUN apt-get update; \
    apt-get install -y openjdk-17-jre
COPY ./bookository-migration/target/bookository-migration-*.jar ./migration.jar
COPY ./bookository-env/dockerfiles/postgres/postgres-migration-1.sh /docker-entrypoint-initdb.d/

# Копирование обложек тестовых книг
COPY ./bookository-migration/src/main/resources/covers/cover-1.jpg ./covers/cover-1.jpg
COPY ./bookository-migration/src/main/resources/covers/cover-2.jpg ./covers/cover-2.jpg
COPY ./bookository-migration/src/main/resources/covers/cover-3.jpg ./covers/cover-3.jpg
COPY ./bookository-migration/src/main/resources/covers/cover-4.jpg ./covers/cover-4.jpg
COPY ./bookository-migration/src/main/resources/covers/cover-5.jpg ./covers/cover-5.jpg

# Копирование файлов книг
#1
COPY ./bookository-migration/src/main/resources/books/book_1/book_1_1.fb2 ./books/book_1/book_1_1.fb2
COPY ./bookository-migration/src/main/resources/books/book_1/book_1_2.txt ./books/book_1/book_1_2.txt
COPY ./bookository-migration/src/main/resources/books/book_1/book_1_3.epub ./books/book_1/book_1_3.epub

#2
COPY ./bookository-migration/src/main/resources/books/book_2/book_2_1.fb2 ./books/book_2/book_2_1.fb2
COPY ./bookository-migration/src/main/resources/books/book_2/book_2_2.epub ./books/book_2/book_2_2.epub
COPY ./bookository-migration/src/main/resources/books/book_2/book_2_3.pdf ./books/book_2/book_2_3.pdf

#3
COPY ./bookository-migration/src/main/resources/books/book_3/book_3_1.epub ./books/book_3/book_3_1.epub
COPY ./bookository-migration/src/main/resources/books/book_3/book_3_2.pdf ./books/book_3/book_3_2.pdf
COPY ./bookository-migration/src/main/resources/books/book_3/book_3_3.txt ./books/book_3/book_3_3.txt

#4
COPY ./bookository-migration/src/main/resources/books/book_4/book_4_1.epub ./books/book_4/book_4_1.epub
COPY ./bookository-migration/src/main/resources/books/book_4/book_4_2.fb2 ./books/book_4/book_4_2.fb2

#5
COPY ./bookository-migration/src/main/resources/books/book_5/book_5_1.epub ./books/book_5/book_5_1.epub
COPY ./bookository-migration/src/main/resources/books/book_5/book_5_2.fb2 ./books/book_5/book_5_2.fb2
COPY ./bookository-migration/src/main/resources/books/book_5/book_5_3.pdf ./books/book_5/book_5_3.pdf
