version: "3"
services:
  postgres:
    image: bookository.migration/postgres:br_it
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookository

  adminer:
    image: adminer:latest
    restart: on-failure
    ports:
      - "8010:8080"
